---
- name: task to Add SSH Key to EC2 Instances
  hosts: full, uf
  become: true
  remote_user: ec2-user
  tasks:
    - name: Copy the Authorized Key File
      authorized_key:
        user: ec2-user 
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    - name: Create a ext4 filesystem on /dev/xvdf
      filesystem:
        fstype: ext4
        dev: /dev/xvdf

    - name: Mount the filesystem to /opt
      mount:
        path: /opt
        src: /dev/xvdf
        state: mounted
        fstype: ext4
