---
- name: Create the Splunk EC2 instances using the build_aws_splunk_instances role
  hosts: localhost
  connection: local
  gather_facts: false
  tags: provisioning
  vars_files:
    - /opt/secrets/aws_secrets.yml
  roles:
   - build_aws_splunk_instances
