---
- name: Create new ec2 Security Group
  ec2_group_info:
    name: "{{ splunk_indexer_security_group }}"
    description: Security Group for webserver Servers
    region: "{{ aws_region }}"
    #aws_access_key: "{{ aws_access_key }}"
    #aws_secret_key: "{{ aws_secret_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8000
        to_port: 8000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8089
        to_port: 8089
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9997
        to_port: 9997
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9887
        to_port: 9887
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Task # 2 Launch the new EC2 Instance
  ec2_instance:
    security_group={{ splunk_indexer_security_group }} 
    instance_type={{ aws_indexer_instance_type }} 
    image_id={{ aws_indexer_image_type }} 
    wait=true 
    region={{ aws_region }} 
    key_name={{ keypair }}
    count={{ total_indexer_instances }}
    #exact_count={{ total_indexer_instances }}
    #count_tag={{ indexer_tag_name }}
  register: ec2

- name: Task # 3 Add Tagging to EC2 instance
  ec2_tag:
    state: present
    region: "{{ aws_region }}"
    tags:
      Name: "{{ indexer_tag_name }}"
      env: "{{ environ }}"
      purpose: " {{ purpose }}"
