---
# tasks file for build_aws_splunk_instances
- name: Task # 1 - Create my security group
  local_action:
    module: ec2_group
    name: "{{ splunk_indexer_security_group }}"
    description: Security Group for webserver Servers
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8000
        to_port: 8000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8089
        to_port: 8089
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9997
        to_port: 9997
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9887
        to_port: 9887
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Task # 2 Launch the new EC2 Instance
  local_action:  ec2
    group={{ splunk_indexer_security_group }} 
    instance_type={{ aws_indexer_instance_type }} 
    image={{ aws_indexer_image_type }} 
    wait=true 
    region={{ aws_region }} 
    keypair={{ keypair }}
    count={{ total_indexer_instances }}
  register: ec2

- name: Task # 3 Add Tagging to EC2 instance
  local_action: ec2_tag resource={{ item.id }} region={{ aws_region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "Indexer"
      env: "{{ environment }}"
      purpose: " {{ purpose }}"
